### ISSUE TITLE
No window decoration under KDE w/ Wayland

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/net.sf.fuse_emulator#1]
This is not the case with other GTK apps like org.gnome.Genius or the version of Fuse in the Fedora 28 repos.

Gpodder has the same issue, though.

**Comment by bertogg** [comment]
Ok, so a problem with client-side decorations. To be honest I don't know what's the status of this and whether the problem is in GTK, KWin, or where.

But after looking at the two examples that you give it seems that disabling the Wayland socket could solve the problem.

Can you try this?

$ flatpak run --nosocket=wayland net.sf.fuse_emulator

If it works I can disable it permanently on the next upload.

**Comment by bertogg** [comment]
Ok, I tried with GNOME + Wayland and there's also problems. In this case the decorations do appear but the window size is wrong.

I got a similar bug reported in Debian: https://bugs.debian.org/872994

Again, disabling the Wayland socket fixes the issue.

**Comment by Alexander-Wilms** [comment]
Thanks, the `flatpak run --nosocket=wayland net.sf.fuse_emulator` workaround does fix the issue.

**Comment by bertogg** [comment]
Ok, I just updated the app in Flathub, if you run flatpak update you'll have the fixed version.

Thanks!
